### ISSUE TITLE
[Mobile] "Go to..." request not executed

### ISSUE THREAD

**Issue by awallin** [mozilla/firefox-voice#1016]
On Android when making a request such as "Go to the BBC" or "Go to the 49ers on ESPN" the action is not executed.

Steps to reproduce:
* Trigger FxVoice helper app
* Say "Go to the BBC"
* App indicates processing and then switches to Firefox browser.
* In Firefox browser the last viewed tab is visible and no other action occurs.

Add on version: 0.19.3886
Mozilla Assistant version 1.0

**Comment by espertus** [comment]
@ianb Does the release version of the add-on support execute.html links? Here's what happens when I try. 
![Screenshot_20200218-094944 (1)](https://user-images.githubusercontent.com/661056/74779961-706a4f80-5253-11ea-9123-a0a10ca805a3.png)

**Comment by ianb** [comment]
Only the special Android build supports those links, but I'm guessing this must be that version because other versions aren't installable on Android.

But if just this one intent is broken, then it probably isn't a problem with execute.html. 

I suspect this is #1020

**Comment by ianb** [comment]
I've fixed #1020, we should reverify this bug.

**Comment by alexandra-martin** [comment]
With Add-on version 0.19.4008 and Mozilla Assistant version 1.0 I can still reproduce the issue.
