### ISSUE TITLE
"Scroll" commands not working in opened Reddit posts

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1247]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed. (if applicable)
Have an active Reddit tab opened and click on a Reddit post.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Scroll" command, e.g. "Scroll down", "Scroll to top" (if page scroll bar is not at the top), "Scroll all the way down".

### Expected result:
Page scrollbar acts accordingly to the command made.

### Actual result:
Nothing happens.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-11).

![19](https://user-images.githubusercontent.com/54401091/76521526-aa52fe00-646d-11ea-8284-cae432ebe893.gif)

**Comment by saucekode** [comment]
Hi, would want to work on this @ianb

**Comment by ianb** [comment]
I'm pretty sure this is also related to #1229 and should be fixed with those

**Comment by alexandra-martin** [comment]
Verified again, but the bug is still reproducing.

![5](https://user-images.githubusercontent.com/54401091/78362483-e0922200-75c2-11ea-8a11-21371c5c4d58.gif)
