### ISSUE TITLE
"Pause", "Stop", "Next", "Skip" commands not working for videos if Youtube tab was firstly opened in a channel page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#422]
### Prerequisites:
Mic and autoplay permissions are enabled.
Make sure that when making the Youtube commands, the Youtube tab was first opened in a channel page.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar and make a "Play" command, e.g. "Play Foo on Youtube".
2. On the opened Youtube channel page tab, select one or more videos from the present page.
3. Use the shortcut or click on the mic icon from the browser toolbar in the Youtube tab.
4. Say or write a "Pause" command.

### Expected result:
The Youtube video is paused.

### Actual result:
The Youtube video continues playing.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Reproduced also for the "Stop", "Skip" and "Next" commands. (second gif)
It seems the commands will not work in this kind of tab, even if several videos are opened.

![3](https://user-images.githubusercontent.com/54401091/66831178-c22a6280-ef5f-11e9-837b-fb2d8b8f0d77.gif)

![4](https://user-images.githubusercontent.com/54401091/66831279-f0a83d80-ef5f-11e9-9d22-8242fff31e97.gif)

**Comment by ianb** [comment]
This probably requires changing/improving the `extension/services/youtube/player.js` script, so it can recognize some more of these cases.

**Comment by JanviMahajan14** [comment]
i would like to work on this issue.

**Comment by melvin2016** [comment]
I would like to work on this issue.

**Comment by melvin2016** [comment]
@ianb I have made a PR #1171 . Is this ok?

**Comment by ianb** [comment]
@melvin2016 says this has been resolved along the way, @alexandra-martin can you re-verify?

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 75.0a1 (2020-03-09).
The reported bug is not fixed yet, as the issue is still reproducing after following the steps described. What is changed is that "Play Foo on Youtube" from step 1 doesn't open the Foo Youtube channel anymore, for me at least. Some other "Play" commands that can reproduce the issue are "Play Twenty One Pilots on Youtube", "Play RAM on Youtube".
"Next" command seems to have some issues, which will be addressed in another bug report.

![17](https://user-images.githubusercontent.com/54401091/76224303-543f4a00-6224-11ea-8b2f-1a629006424d.gif)

One important note: If the Youtube channel that is opened with the "Play" command from step 1 doesn't have a video preview, the issue will not be reproduced. (e.g. "Play Radiohead on Youtube")

![16](https://user-images.githubusercontent.com/54401091/76223381-0de9eb00-6224-11ea-9c59-f0b58dfc36e9.gif)

**Comment by melvin2016** [comment]
Ok let me look at it again.

**Comment by melvin2016** [comment]
@ianb @alexandra-martin I have opened a PR #1244 . Please review.

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-13).

![4](https://user-images.githubusercontent.com/54401091/76626356-b3ad9a80-6541-11ea-84ed-ee0d9ee487af.gif)

**Comment by melvin2016** [comment]
Thanks for verifying :) @alexandra-martin
